repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.5
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: flake8
-   repo: https://github.com/asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/asottile/add-trailing-comma
    sha: v0.6.4
    hooks:
    -   id: add-trailing-comma
